version: '3'
services:
  web:
    build: .
    ports:
      - "5050:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

